### ISSUE TITLE
Themes not installing on Alfred 4

### ISSUE THREAD

**Issue by BeMrTeal** [chrismessina/alfred-app#1]
I tried to install on Alfred 4 with no success.

Cheers

**Comment by chrismessina** [comment]
Wow, you're fast! 

Are you getting an error?

**Comment by BeMrTeal** [comment]
Wow, you are slow.  😝

It took only one year to reply.

I got it sorted later.

**Comment by chrismessina** [comment]
OMG, ha! I just updated it yesterday so hadn't seen your issue. 

IT TOOK LITERALLY A YEAR! 🤣
